import "./globals.css";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.Layout = ({ children }) => {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
};
export default RootLayout;
